config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit; end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="container p-5 m-3">
  <%= simple_form_for(article) do |f| %>
    <strong><%= f.input :title %></strong>
    <strong><%= f.input :content %></strong>
    <%= f.submit class: 'btn btn-success w-100 mt-3'%>
  <% end %>
  <%= link_to 'home', root_path, class: 'btn btn-primary btn-lg btn-block w-100 mt-3' %>
</div>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<div class="container-bg">
  <div class="container">
    <h1 class='text-left'>Wikinimous</h1>
    <%= link_to 'Add a new article', new_article_path, class: 'btn btn-sm btn-success mb-5' %>
    <% @articles.each do |article| %>
      <%= link_to article_path(article), class: 'text-decoration-none text-success' do %>
        <div class="card text-white bg-success mb-3">
          <h2><%= article.title %></h2>
          <p><%= article.content %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<div class="container">
  <h3><%= @article.title %></h3>
  <div class='card text-white bg-secondary mb-3'>
    <p>Content: <%= @article.content %></p>
  </div>
  <%= link_to 'home', root_path, class: 'btn btn-sm btn-success' %>
  <%= link_to 'edit', edit_article_path(@article), class: 'btn btn-sm btn-primary' %>
  <%= link_to 'delete', article_path(@article),
    class: 'btn btn-sm btn-danger',
    method: :delete,
    data: { confirm: 'Are you sure you want to delete?'} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>